# Dataframes accessors

In [37]:
import numpy as np
import pandas as pd
from physipy import m, units
from physipandas import QuantityArray, QuantityDtype
J = units["J"]
mm = units["mm"]

We mix several datatypes : 
 - int
 - quantity with SI units
 - quantity without unit
 - quantity with non-SI units

In [44]:
df = pd.DataFrame({
    "np_arr":np.arange(10),                                                # numpy array
    "physipy_arr": pd.Series(QuantityArray(np.arange(10)*m)),              # quantity array 
    "dimless":     pd.Series(QuantityArray(np.arange(10)**2)),             # squared meter
    "squaredm":    pd.Series(QuantityArray(np.arange(10)*m**2)),           # squared mete
    "power":       pd.Series(QuantityArray(np.random.normal(size=10)*J)),  # Joules
   # "lost_units":  pd.Series(np.arange(10)*m),    
    "favunit":     pd.Series(QuantityArray((np.arange(10)*m).set_favunit(mm))),
})
print(df.dtypes)
df

np_arr                         int64
physipy_arr               physipy[m]
dimless                    physipy[]
squaredm               physipy[m**2]
power          physipy[kg*m**2/s**2]
favunit                   physipy[m]
dtype: object

   np_arr physipy_arr dimless squaredm                power favunit
0       0           0       0        0  -1.0626779509907804       0
1       1           1       1        1    1.451974571712949       1
2       2           2       4        2   0.7040919373829754       2
3       3           3       9        3  0.12785282959807914       3
4       4           4      16        4 -0.05616748545019974       4
5       5           5      25        5  0.12568458139265926       5
6       6           6      36        6 0.011884257781547987       6
7       7           7      49        7  -0.3095438277916292       7
8       8           8      64        8  -0.9036577823335755       8
9       9           9      81        9    2.047772844157777       9

Show the dataframe with units as a multiindex

In [49]:
df.physipy.show()

,np_arr,physipy_arr,dimless,squaredm,power,favunit,i
unit,-,m,,m**2,kg*m**2/s**2,m,kg*m**2/s**3
0,0,0,0,0,-1.0626779509907804,0,1.3010105122890356
1,1,1,1,1,1.451974571712949,1,1.0612494652662883
2,2,2,4,2,0.7040919373829754,2,2.018374216220103
3,3,3,9,3,0.12785282959807914,3,0.2574405786746649
4,4,4,16,4,-0.05616748545019974,4,-0.8229619313337286
5,5,5,25,5,0.12568458139265926,5,1.2709736561034244
6,6,6,36,6,0.011884257781547987,6,-0.4263064267205049
7,7,7,49,7,-0.3095438277916292,7,-0.48186164258835595
8,8,8,64,8,-0.9036577823335755,8,-0.3043432976576113
9,9,9,81,9,2.047772844157777,9,-1.0321855061512932

In [47]:
df["i"] = QuantityArray(np.random.normal(0, 1, 10)*units["W"])
print(df.dtypes)
df

np_arr                         int64
physipy_arr               physipy[m]
dimless                    physipy[]
squaredm               physipy[m**2]
power          physipy[kg*m**2/s**2]
favunit                   physipy[m]
i              physipy[kg*m**2/s**3]
dtype: object

,np_arr,physipy_arr,dimless,squaredm,power,favunit,i
0,0,0,0,0,-1.0626779509907804,0,1.3010105122890356
1,1,1,1,1,1.451974571712949,1,1.0612494652662883
2,2,2,4,2,0.7040919373829754,2,2.018374216220103
3,3,3,9,3,0.12785282959807914,3,0.2574405786746649
4,4,4,16,4,-0.05616748545019974,4,-0.8229619313337286
5,5,5,25,5,0.12568458139265926,5,1.2709736561034244
6,6,6,36,6,0.011884257781547987,6,-0.4263064267205049
7,7,7,49,7,-0.3095438277916292,7,-0.48186164258835595
8,8,8,64,8,-0.9036577823335755,8,-0.3043432976576113
9,9,9,81,9,2.047772844157777,9,-1.0321855061512932

In [51]:
df["e"] = 2/df["i"]
df["f"] = np.sqrt(df["i"])
df.physipy.show()

/Users/mocquin/MYLIB10/MODULES/physipy/physipy/quantity/quantity.py:854: RuntimeWarning: invalid value encountered in sqrt
  res = ufunc.__call__(left.value)

,np_arr,physipy_arr,dimless,squaredm,power,favunit,i,e,f
unit,-,m,,m**2,kg*m**2/s**2,m,kg*m**2/s**3,s**3/(kg*m**2),kg**0.5*m**1.0/s**1.5
0,0,0,0,0,-1.0626779509907804,0,1.3010105122890356,1.5372665947803466,1.140618477971068
1,1,1,1,1,1.451974571712949,1,1.0612494652662883,1.8845710320317202,1.0301696293651295
2,2,2,4,2,0.7040919373829754,2,2.018374216220103,0.9908965264853051,1.420694976488656
3,3,3,9,3,0.12785282959807914,3,0.2574405786746649,7.768783034501556,0.5073860253048609
4,4,4,16,4,-0.05616748545019974,4,-0.8229619313337286,-2.43024607074924,NaN
5,5,5,25,5,0.12568458139265926,5,1.2709736561034244,1.5735967385285063,1.1273746742336481
6,6,6,36,6,0.011884257781547987,6,-0.4263064267205049,-4.691461058623075,NaN
7,7,7,49,7,-0.3095438277916292,7,-0.48186164258835595,-4.15056900826729,NaN
8,8,8,64,8,-0.9036577823335755,8,-0.3043432976576113,-6.571526349990517,NaN
9,9,9,81,9,2.047772844157777,9,-1.0321855061512932,-1.9376361982231214,NaN

## Read from file with units

In [53]:
df = pd.read_csv("physidata.csv",header=[0,1])
df

  height weight speed power
       m     kg   m/s     W
0      1      2     3     4
1      5      6     7     8
2      9     10    11    12